### ISSUE TITLE
ActivityCardViewBinding Missing Class

### ISSUE THREAD

**Issue by muhammadameen** [alphamu/FrostyBackgroundTestApp#1]
I tried your code and found in android studio that ActivityCardViewBinding class giving continous error and android studio did not recognize it, please share with me this class

**Comment by alphamu** [comment]
This seems to be data-binding related. I don't recall using data-binding in this application. I'll take a look and get back to you.

**Comment by alphamu** [comment]
Works just fine for me, thats a generated class, you need to make sure your version of Android Studio supports data binding.
